// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaezagpjlwrnyrryfano.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZXphZ3BqbHdybnlycnlmYW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODk2NDUsImV4cCI6MjA3Mzc2NTY0NX0.pebPxLh0OpVht9cRaZ1R8oIO_xYd00feJi4XmXuueYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});